### ISSUE TITLE
Notice: Undefined offset: 3 in decode_asc.php on line 165 

### ISSUE THREAD

**Issue by Collusion** [Collusion/pickmybrain#2]
@apex1310 Discovered this bug:

Notice: Undefined offset: 3 in decode_asc.php on line 165 

![decode_notice](https://github.com/user-attachments/assets/b1425c9d-985c-4961-ada7-60efff8eaa38)

Have not been able to reproduce the issue yet

**Comment by Collusion** [comment]
@apex1310 Does this also happen if your keyword is "naslo" ? (with the double quotes)

**Comment by apex1310** [comment]
yup

![Screenshot 2024-12-28 133255](https://github.com/user-attachments/assets/81616c07-8c7f-4a5b-9815-9af89c17d579)

**Comment by apex1310** [comment]
this is my settings file just for info, maybe im doing something wrong.

`

; database indexes
use_internal_db			= 1
main_sql_query			= "select title, description from mydb order by id asc"
main_sql_attrs[]                = ""
use_buffered_queries 		= 0
ranged_query_value		= 0
html_strip_tags			= 1
html_remove_elements		= ""
include_original_data	= 1
html_index_attrs[]              = ""

; common indexer settings
indexing_interval		= 0
update_interval			= 1440
sentiment_analysis		= 1
prefix_mode			= 3
prefix_length			= 3
dialect_processing		= 1
charset				= "0-9a-zöäåšđčćž#$"
blend_chars[]                   = "."
blend_chars[]                   = "-"
blend_chars[]                   = "&"
ignore_chars[]                  = "'"
separate_alnum			= 1
delta_indexing			= 0
delta_merge_interval	= 2880
synonyms[]                      = ""
					
; runtime
field_weights[description]             = "2"
field_weights[title]           = "1"
sentiweight			= 1
keyword_stemming		= 1
dialect_matching		= 1
quality_scoring			= 1
forgive_keywords		= 1
expansion_limit			= 32
log_queries			= 0
keyword_suggestions		= 1

; general settings
admin_email			= ""
mysql_data_dir			= ""
dist_threads			= 1
innodb_row_format		= 0
enable_exec			= 0

; do not edit !
data_columns[]                  = "title"
data_columns[]                  = "description"
number_of_fields		= 2
index_type			= 2
xpdf_folder			= "xpdf_win/bin64/pdftotext.exe"
document_root			= "C:/xampp/htdocs"

**Comment by Collusion** [comment]
Would you be able to give me a small data dump from your PMBTokens table with the following SQL query? 

SELECT checksum, token, metaphone, doc_matches, max_doc_id, HEX(doc_ids) FROM PMBTokens_X WHERE token = 'keyword'

Where PMBTokens_X denotes your index id, like PMBTokens_1

And preferably for a keyword that returns over 10 000 results by itself, e.g. "naslo"

**Comment by apex1310** [comment]
im running some test to see if there  is maybe tables character encoding problem bacause im using UTF-8.

**Comment by apex1310** [comment]
![Screenshot 2024-12-28 151822](https://github.com/user-attachments/assets/4d54b300-138a-4945-8b0a-9c44931fc904)

**Comment by apex1310** [comment]
![Screenshot 2024-12-28 152316](https://github.com/user-attachments/assets/56ae82aa-631a-4492-b82e-00b4c980a6bf)

**Comment by apex1310** [comment]
if i query for "naslo" there is no records because that word is non existent in any row. Why is pmb showing over 14.000 results i don't know

**Comment by Collusion** [comment]
Are you able to paste all data from the "pežo" row? I'd like to have a closer look in the binary data in doc_ids, but I'd need the whole string for that

**Comment by Collusion** [comment]
Also, there's no preg_replace() call in line 4195 of PMBApi.php, so I wonder if you've modified the file somehow?

**Comment by apex1310** [comment]
i have this line in pmbapi.php on line 4195. I did not temper with any file since download

$string = preg_replace('/\b'.preg_quote($chunk,"/").'\b/iu', '<b>$0</b>', $string);

**Comment by Collusion** [comment]
That is strange, all of my code editors & Github's code viewer show that function call on line 4200. 

![image](https://github.com/user-attachments/assets/8795ac5a-af8d-4da5-bc55-9692683ba9fb)

Do you have the latest version of PMBApi.php ?

**Comment by apex1310** [comment]
no i see now that it was updated yesterday, i didn't see that

**Comment by apex1310** [comment]
i would like to send you my database dump because i am struggling with this whole day with no result. I have used some other database with dummy generated text and i have same errors. I think is the bast way to test my database with same queries and see what would you get as result. May I send you link to my database dump to your mail?

**Comment by Collusion** [comment]
Please go ahead! Also include a copy of your settings file, if possible.

My email address was: henri.ruutinen@pickmybra.in

**Comment by apex1310** [comment]
i have sent you fies

my current server conf

XAMPP v3.3.0
Apache/2.4.48 (Win64) OpenSSL/1.1.1l PHP/7.3.30
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.3.30

**Comment by Collusion** [comment]
Thank you, database dump received. I was now able to replicate the issue with the data you provided. 

Starting to investigate why this happens...

**Comment by Collusion** [comment]
I just released fixed versions of decode_asc.php & bin32/decode_asc.php files. Can you try them out and see if the problem still persists?

**Comment by apex1310** [comment]
nice, no problem now. Thank you man!

**Comment by Collusion** [comment]
No problem!

**Comment by apex1310** [comment]
please save dump just for now
